In [2]:
import numpy as np

In [3]:
np.version.full_version

'2.0.2'

## create an array i.e similar to list

In [4]:
a=np.array([0,1,2,3,4,5])

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [7]:
a.shape

(6,)

In [48]:
#Create a 1D NumPy array of numbers from 0 to 9
arr = np.arange(10)
print(arr)        # [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [49]:
#Create a 1D array filled with zeros of size 10
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
#Create a 1D array filled with ones of size 5
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [51]:
#Array of numbers from 10 to 50 with step size 5

step_arr = np.arange(10, 55, 5)
print(step_arr)   # [10 15 20 25 30 35 40 45 50]

[10 15 20 25 30 35 40 45 50]


In [52]:
#Array of 10 random numbers between 0 and 1
rand_nums = np.random.rand(10)
print(rand_nums)

[0.88414963 0.5630184  0.31460327 0.31919533 0.01437391 0.14265183
 0.95813636 0.56657988 0.02397953 0.94054783]


In [53]:
#Create a 3x3 identity matrix
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## transform this arrya into a 2D matrix

In [8]:
b= a.reshape((3,2)) #r,c
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(3, 2)

In [11]:
## it avoids copies wherever possible

In [12]:
b[1][0]=77

In [13]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [14]:
a # we can iimediately see the  same changes reflecte in a as well 

array([ 0,  1, 77,  3,  4,  5])

In [54]:
A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
B = np.array([[9, 8, 7],
                  [6, 5, 4],
                  [3, 2, 1]])

In [57]:
#S#hape and size of A
print(A.shape)   # (3, 3)
print(A.size)    # 9


(3, 3)
9


In [58]:
#First row of A
print(A[0])      # [1 2 3]


[1 2 3]


In [59]:
#Second column of A
print(A[:,1])    # [2 5 8]

[2 5 8]


In [60]:
A + B

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [61]:
A-B

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [62]:
A*B

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [64]:
#Transpose of A
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## keep in mind when you need true copy

In [15]:
c = a.reshape((3,2)).copy()

In [16]:
c[0][0]=-99

In [17]:
a,c # here c and a are totally independent copy

(array([ 0,  1, 77,  3,  4,  5]),
 array([[-99,   1],
        [ 77,   3],
        [  4,   5]]))

## operations are propagated to the individual elements

In [18]:
a*2

array([  0,   2, 154,   6,   8,  10])

In [19]:
a**2 #where as in list what will happend if we do [1,2,3,4,5]*2

array([   0,    1, 5929,    9,   16,   25])

## indexing power of numpy 

In [24]:
a

array([ 0,  1, 77,  3,  4,  5])

In [25]:
a[np.array([0,2,3])]

array([ 0, 77,  3])

In [26]:
# in addition to fact that condition are now  propagated to the inndividual elements 
a>4

array([False, False,  True, False, False,  True])

In [27]:
a[a>4]

array([77,  5])

In [28]:
# this can also be used to trim outiers

In [47]:
a[a>4]=5
a

array([0, 1, 5, 3, 4, 5])

In [65]:
arr = np.arange(10, 20)   # [10 11 12 13 14 15 16 17 18 19]
# First 3 elements

print(arr[:3])   # [10 11 12]

[10 11 12]


In [67]:
#Last 2 elements
print(arr[-2:])  # [18 19]


[18 19]


In [68]:
#Elements from index 3 to 7

print(arr[3:8])  # [13 14 15 16 17]

[13 14 15 16 17]


In [69]:
#Every second element
print(arr[::2])  # [10 12 14 16 18]

[10 12 14 16 18]


In [70]:
#Reverse the array
print(arr[::-1]) # [19 18 17 16 15 14 13 12 11 10]


[19 18 17 16 15 14 13 12 11 10]


In [71]:
#Change value at index 2 to 100
arr[2] = 100
print(arr)

[ 10  11 100  13  14  15  16  17  18  19]


In [72]:
#Select elements greater than 15
print(arr[arr > 15])  

[100  16  17  18  19]


## Create a 5×5 matrix with values 1,2,3,…,25 and reshape it to 25×1
## Generate an array of 100 random numbers between -10 and 10. Replace all negative values with 0.

## Create a 10×10 matrix where the border elements are 1 and the inside elements are 0.

## Create a checkerboard pattern (8×8) using only NumPy slicing.


## Normalize a random 1D array of size 10 so that its sum equals 1.


In [84]:
arr = np.arange(1, 26)
matrix_5X5= arr[:25].reshape(5,5)
matrix_5X5.reshape(1,25)

#Generate 100 random numbers between -10 and 10, replace negatives with 0

rand_arr = np.random.randint(-10, 11, 100)
rand_arr[rand_arr < 0] = 0
print(rand_arr)


#Create a 10×10 matrix with border = 1, inside = 0

mat = np.ones((10,10))
mat[1:-1, 1:-1] = 0
print(mat)
#arr[1:-1] excludes the first and last elements.So in 2D:
#mat[1:-1, 1:-1] means:
#Rows from index 1 to -2 (skip first & last row).
#Columns from index 1 to -2 (skip first & last column)

[ 7  0  0  0  0  0  0  0  0  0  1  8  0  0  0  0  0  0  0  0  0  0  0  7
  7  7  0  0  3  4  4  3  2  0  0  0 10  3  0  0  9  0  0  7  4  0  4  0
  0  0  3  0  4  7  2  0  0  1  8  6  0  8  7  2  8  9  7  0  0  0  0  0
  0  1  0  2  1  3 10  0  2  4  0  0  0  6  0  0  0  1  0  2  7  0  9  0
  0  7  7  3]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [85]:
#Checkerboard pattern (8×8)
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [86]:
arr = np.random.rand(10)
normalized = arr / arr.sum()
print(normalized, normalized.sum())

[0.1267622  0.07249695 0.0482676  0.09370812 0.0060962  0.18589734
 0.05745696 0.138372   0.25373289 0.01720974] 0.9999999999999999


In [91]:
#Indexing & Slicing (7 exercises)
arr = np.arange(1, 26).reshape(5, 5)
    # [[ 1  2  3  4  5]
    #  [ 6  7  8  9 10]
    #  [11 12 13 14 15]
    #  [16 17 18 19 20]
    #  [21 22 23 24 25]]

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
#Middle 3×3 submatrix
print(arr[1:4, 1:4])


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [94]:
#Reverse rows
print(arr[::-1, :])

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [95]:
#Reverse columns
print(arr[:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [96]:
#Every second element of last row
print(arr[-1, ::2])   # [21 23 25]

[21 23 25]


In [97]:
#All corner elements
corners = [arr[0,0], arr[0,-1], arr[-1,0], arr[-1,-1]]
print(corners)

[np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


In [ ]:
#Advanced Array Indexing 
arr = np.array([[5, 2, 9],
                    [1, 7, 3],
                    [8, 4, 6]])

In [ ]:
#Extract elements (0,2), (1,1), (2,0)
print(arr[(0,1,2), (2,1,0)])   # [9 7 8]


In [ ]:
#Replace even numbers with -1
arr_even = arr.copy()
arr_even[arr_even % 2 == 0] = -1
print(arr_even)