In [4]:
# Create a Numeric Vector
x <- c(10, 20, 30, 40, 50)
x
#Explanation: Creates a numeric vector using the c() function.

[1] 10 20 30 40 50

In [5]:
#Create a Character Vector
fruits <- c("Apple", "Banana", "Mango", "Orange")
fruits
# Explanation: Creates a vector of character strings.

[1] "Apple"  "Banana" "Mango"  "Orange"

In [6]:
#Create a Logical Vector
status <- c(TRUE, FALSE, TRUE, FALSE)
status
#Explanation: Creates a vector containing logical values.

[1]  TRUE FALSE  TRUE FALSE

In [7]:
#. Find the Length of a Vector
x <- c(5, 10, 15, 20, 25)
length(x)

#Explanation: Returns the number of elements in the vector.

[1] 5

In [8]:
# Access Vector Elements
x <- c(5, 10, 15, 20, 25)
x[1]
x[5]

#Explanation: Accesses the first and fifth elements of the vector.

[1] 5

[1] 25

In [9]:
# Create a Sequence from 1 to 10
seq(1, 10)
#Explanation: Generates numbers from 1 to 10.

[1]  1  2  3  4  5  6  7  8  9 10

In [11]:
# Create a Sequence with Step Size
seq(5, 50, by = 5)

#Explanation: Generates numbers from 5 to 50 with an interval of 5.


[1]  5 10 15 20 25 30 35 40 45 50

In [12]:
# Create a Descending Sequence
seq(20, 1, by = -1)

#Explanation: Generates numbers from 20 down to 1.

[1] 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [13]:
# Create 10 Equally Spaced Numbers

seq(0, 1, length.out = 10)

#Explanation: Generates 10 equally spaced numbers between 0 and 1.

[1] 0.0000000 0.1111111 0.2222222 0.3333333 0.4444444 0.5555556 0.6666667
 [8] 0.7777778 0.8888889 1.0000000

In [14]:
# Repeat a Number
rep(5, times = 10)

[1] 5 5 5 5 5 5 5 5 5 5

In [16]:
# Repeat a Vector

rep(c(1, 2, 3), times = 4)

#Explanation: Repeats the vector four times.

[1] 1 2 3 1 2 3 1 2 3 1 2 3

In [17]:
# Repeat Each Element

rep(c(10, 20, 30), each = 3)

#Explanation: Repeats each element three times before moving to the next.

[1] 10 10 10 20 20 20 30 30 30

In [18]:
# Repeat Characters

rep(c("A", "B", "C"), times = 5)

#Explanation: Repeats the character vector five times.

[1] "A" "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C" "A" "B" "C"

In [19]:
# Create a Mixed Pattern
rep(1:5, each = 2)
#Explanation: Repeats every number twice.

[1] 1 1 2 2 3 3 4 4 5 5

In [20]:
# Create a Simple List
student <- list(Name = "Rahul", Age = 22, Marks = 89)
student

# Explanation: Creates a list containing different data types.

$Name
[1] "Rahul"

$Age
[1] 22

$Marks
[1] 89

In [23]:
#  Access a List Element
student$Name
student$age
student$Age



[1] "Rahul"

NULL

[1] 22

In [37]:
# Create a List with Different Objects
mylist <- list(c(1,2,3), c("A","B"), c(TRUE,FALSE))
mylist
print('########')
mylist[3]

# Explanation: Creates a list containing numeric, character, and logical vectors.

[[1]]
[1] 1 2 3

[[2]]
[1] "A" "B"

[[3]]
[1]  TRUE FALSE

[1] "########"


[[1]]
[1]  TRUE FALSE

In [38]:
# Create a 2×3 Array
arr <- array(1:6, dim = c(2,3))
arr

1,3,5
2,4,6


In [44]:
# Create a 3-D Array
arr3d <- array(1:36, dim = c(3,3,4))
print (arr3d)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27

, , 4

     [,1] [,2] [,3]
[1,]   28   31   34
[2,]   29   32   35
[3,]   30   33   36



In [1]:
# create two 2 by 3 matrix
array1 <- array(c(1:12), dim = c(2,3,2))

print(array1)
#In the above example, we have used the array() function to create an array named array1. 
#Notice the arguments passed inside array(),

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12



In [3]:
print(array(c(1:15), dim = c(2,3,2)))
#Finally, the numbers from 1 to 12 that are arranged in two 2 by 3 matrices are printed.

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

